name: Daily input

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Scrape input
        run: | 
          curl https://raw.githubusercontent.com/stayari/advent-of-code-22/main/input/test.txt > new_file
      - name: Github
        run: git status
      - name: commit 
        run: git add . 
      - name: push 
        run: git push
        
